is_college: true

teachers:
  - reviewteacher

periods:
  - id: p1
    name: 1st
    students: [ reviewstudent1, reviewstudent2, reviewstudent3 ]
  - id: p2
    name: 2nd
    students: [ reviewstudent4, reviewstudent5, reviewstudent6 ]
