<%= File.read(File.join(File.dirname(__FILE__), '../../review_course.yml')) %>

course_name: AP US History Review
salesforce_book_name: AP US History

assignments:
  - type: reading
    book_locations: [[1, 1], [1, 2], [1, 3], [1, 4]]
    title: Read Chapter 1
    periods:
      - id: p1
        opens_at: <%= open_last_monday %>
        due_at: <%= due_next_monday + 2.days %>
        students: { reviewstudent1: 100, reviewstudent2: 80, reviewstudent3: i }
      - id: p2
        opens_at: <%= open_last_monday %>
        due_at: <%= due_next_monday + 2.days %>
        students: { reviewstudent4: 100, reviewstudent5: 80, reviewstudent6: i }
