<%= File.read(File.join(File.dirname(__FILE__), '../../review_course.yml')) %>

course_name: Physics with Courseware Review
salesforce_book_name: Physics w Courseware

assignments:
  - type: reading
    book_locations: [[1, 0], [1, 1], [1, 2]]
    title: Read Chapter 1
    periods:
      - id: p1
        opens_at: <%= open_last_monday - 2.week %>
        due_at: <%= due_last_monday - 5.days %>
        students: { reviewstudent1: 100, reviewstudent2: 80, reviewstudent3: i }
      - id: p2
        opens_at: <%= open_last_monday - 2.week %>
        due_at: <%= due_last_monday - 5.days %>
        students: { reviewstudent4: 100, reviewstudent5: 80, reviewstudent6: i }

  - type: reading
    book_locations: [[2, 0], [2, 1], [2, 2]]
    title: Read Chapter 2
    periods:
      - id: p1
        opens_at: <%= open_last_monday - 1.week %>
        due_at: <%= due_last_monday + 2.days %>
        students: { reviewstudent1: 100, reviewstudent2: 80, reviewstudent3: i }
      - id: p2
        opens_at: <%= open_last_monday - 1.week %>
        due_at: <%= due_last_monday + 2.days %>
        students: { reviewstudent4: 100, reviewstudent5: 80, reviewstudent6: i }

  - type: reading
    book_locations: [[3, 0], [3, 1], [3, 2]]
    title: Read Chapter 3
    periods:
      - id: p1
        opens_at: <%= open_last_monday %>
        due_at: <%= due_next_monday + 2.days %>
        students: { reviewstudent1: 100, reviewstudent2: 80, reviewstudent3: i }
      - id: p2
        opens_at: <%= open_last_monday %>
        due_at: <%= due_next_monday + 2.days %>
        students: { reviewstudent4: 100, reviewstudent5: 80, reviewstudent6: i }

  - type: reading
    book_locations: [[4, 0], [4, 1], [4, 2]]
    title: Read Chapter 4
    periods:
      - id: p1
        opens_at: <%= open_next_monday %>
        due_at: <%= due_next_monday + 9.days %>
        students: { reviewstudent1: ns, reviewstudent2: ns, reviewstudent3: ns }
      - id: p2
        opens_at: <%= open_next_monday %>
        due_at: <%= due_next_monday + 9.days %>
        students: { reviewstudent4: ns, reviewstudent5: ns, reviewstudent6: ns }

  - type: homework
    book_locations: [[1, 0], [1, 1], [1, 2]]
    title: HW Chapter 1
    num_exercises: 3
    periods:
      - id: p1
        opens_at: <%= open_last_monday - 2.weeks %>
        due_at: <%= due_last_monday - 3.days %>
        students: { reviewstudent1: 100, reviewstudent2: 80, reviewstudent3: i }
      - id: p2
        opens_at: <%= open_last_monday - 2.weeks %>
        due_at: <%= due_last_monday - 3.days %>
        students: { reviewstudent4: 100, reviewstudent5: 80, reviewstudent6: i }

  - type: homework
    book_locations: [[2, 0], [2, 1], [2, 2]]
    title: HW Chapter 2
    num_exercises: 3
    periods:
      - id: p1
        opens_at: <%= open_last_monday - 1.week %>
        due_at: <%= due_last_monday + 4.days %>
        students: { reviewstudent1: 100, reviewstudent2: 80, reviewstudent3: i }
      - id: p2
        opens_at: <%= open_last_monday - 1.week %>
        due_at: <%= due_last_monday + 4.days %>
        students: { reviewstudent4: 100, reviewstudent5: 80, reviewstudent6: i }

  - type: homework
    book_locations: [[3, 0], [3, 1], [3, 2]]
    title: HW Chapter 3
    num_exercises: 3
    periods:
      - id: p1
        opens_at: <%= open_last_monday %>
        due_at: <%= due_next_monday + 4.days %>
        students: { reviewstudent1: 100, reviewstudent2: 80, reviewstudent3: i }
      - id: p2
        opens_at: <%= open_last_monday %>
        due_at: <%= due_next_monday + 4.days %>
        students: { reviewstudent4: 100, reviewstudent5: 80, reviewstudent6: i }

  - type: homework
    book_locations: [[4, 0], [4, 1], [4, 2]]
    title: HW Chapter 4
    num_exercises: 3
    periods:
      - id: p1
        opens_at: <%= open_next_monday %>
        due_at: <%= due_next_monday + 11.days %>
        students: { reviewstudent1: ns, reviewstudent2: ns, reviewstudent3: ns }
      - id: p2
        opens_at: <%= open_next_monday %>
        due_at: <%= due_next_monday + 11.days %>
        students: { reviewstudent4: ns, reviewstudent5: ns, reviewstudent6: ns }
