version: '3.5'
services:
  app:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/code
      - /code/tmp
      - /code/log
    secrets:
      - hypothesis
    networks:
      - tutor
      - openstax
    environment:
      - HYPOTHESIS_HOST=127.0.0.1
      - REDIS_URL=redis://redis:6379/0
      - OXT_DB_HOST=postgres
  redis:
    image: "redis:latest"
    networks:
      - tutor
  postgres:
    image: "postgres:9.5"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - tutor
    environment:
      - POSTGRES_USER=ox_tutor
      - POSTGRES_PASSWORD=ox_tutor_secret_password
      - POSTGRES_DB=ox_tutor_dev
networks:
  tutor:
  openstax:
    name: openstax
volumes:
  pgdata:
secrets:
  hypothesis:
    file: /tmp/hypothesis-credentials/env
