<%= File.read(File.join(File.dirname(__FILE__), '../../courseware_book.yml')) %>

salesforce_book_name: Sociology w Courseware
appearance_code: intro_sociology
default_course_name: Sociology with Courseware
cnx_book_id: 02040312-72c8-441e-a685-20e9333f3e1d

reading_processing_instructions:
- css: .section-quiz, .short-answer, .further-research, [data-element-type="section-quiz"],
    [data-element-type="short-answer"], [data-element-type="further-research"],
    [data-type="glossary"]
  fragments: []
