reviewteacher: Review Teacher
teacher01:     Charles Morris
teacher02:     Redmond Blake
teacher03:     C. E. Tripp
teacher04:     J. D. Ballard
teacher05:     Trent Deckow
teacher06:     Adah Kuhn
teacher07:     Yoshiko Roob
teacher08:     Okey Gottlieb
